[project]
name = "fundrive-webdav"
version = "1.2.28"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [ "webdav4>=0.10.0",]
[[project.authors]]
name = "farfun"
email = "farfarfun@qq.com"

[tool.uv.sources.fundrive]
workspace = true
